site_name: MarkdownFlow Documentation
site_url: https://markdownflow.ai/docs/
site_description: Complete documentation for MarkdownFlow
site_author: MarkdownFlow Team

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: syntax/index.md
  - Syntax Guide:
    - Variables: syntax/variables.md
    - User Input: syntax/user-input.md
    - AI Instructions: syntax/ai-instructions.md
    - Examples: syntax/examples.md
  - Libraries:
    - Overview: libraries/index.md
    - Frontend:
      - markdown-flow-ui: libraries/frontend/markdown-flow-ui.md
      - remark-flow: libraries/frontend/remark-flow.md
      - markdown-it-flow: libraries/frontend/markdown-it-flow.md
    - Backend:
      - Python Agent: libraries/backend/agent-python.md
      - Go Agent: libraries/backend/agent-go.md
