site_name: MarkdownFlow Documentation
site_url: https://markdownflow.ai/docs/
site_description: Complete documentation for MarkdownFlow
site_author: MarkdownFlow Team

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Getting Started:
    - index.md
    - Complete Example: getting-started/example.md
    - How It Works: getting-started/how-it-works.md
    - Quick Start (5 min): getting-started/quickstart.md
    - Installation: getting-started/installation.md
    - vs Markdown: getting-started/relationship.md
  - Specification:
    - Overview: specification/overview.md
    - How It Works: specification/how-it-works.md
    - Variables: specification/variables.md
    - Buttons & Input: specification/button-input.md
    - Preserved Output: specification/preserved-output.md
  - SDKs:
    - Overview: sdks/index.md
    - JavaScript:
      - markdown-flow-ui (React): sdks/javascript/markdown-flow-ui.md
      - remark-flow (React): sdks/javascript/remark-flow.md
      - markdown-it-flow (Vue/Vanilla): sdks/javascript/markdown-it-flow.md
    - Python: sdks/python.md
    - Go: sdks/go.md
  - Examples:
    - Overview: examples/index.md
    - Education: examples/education.md
    - Storytelling: examples/storytelling.md
    - Forms & Surveys: examples/forms.md
    - Documentation: examples/documentation.md
    - Consultation: examples/consultation.md
  - Ecosystem:
    - Overview: ecosystem/index.md
