site_name: MarkdownFlow Documentation
site_url: https://markdownflow.ai/docs/
site_description: Complete documentation for MarkdownFlow
site_author: MarkdownFlow Team

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Specification:
    - Overview: specification/index.md
    - Variables: specification/variables.md
    - User Input: specification/user-input.md
    - AI Instructions: specification/ai-instructions.md
  - SDKs:
    - Overview: sdks/index.md
    - JavaScript:
      - markdown-flow-ui (React): sdks/javascript/markdown-flow-ui.md
      - remark-flow (React): sdks/javascript/remark-flow.md
      - markdown-it-flow (Vue/Vanilla): sdks/javascript/markdown-it-flow.md
    - Python: sdks/python.md
    - Go: sdks/go.md
  - Examples:
    - Overview: examples/index.md
    - Education: examples/education.md
    - Storytelling: examples/storytelling.md
    - Forms & Surveys: examples/forms.md
    - Documentation: examples/documentation.md
    - Consultation: examples/consultation.md
  - Ecosystem:
    - Overview: ecosystem/index.md
