site_name: MarkdownFlow Documentation
site_url: https://markdownflow.ai/docs/
site_description: Complete documentation for MarkdownFlow
site_author: MarkdownFlow Team

repo_url: https://github.com/ai-shifu/markdown-flow
repo_name: ai-shifu/markdown-flow
edit_uri: edit/main/docs/docs/

theme:
  name: material
  logo: assets/logo-white.svg
  favicon: assets/logo-color.svg
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

extra:
  homepage: /
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ai-shifu/markdown-flow
      name: GitHub Repository

extra_css:
  - stylesheets/extra.css

# Remove external mermaid - Material has built-in support

plugins:
  - search:
      lang: en
  - social:
      cards: true
      cards_color:
        fill: "#0F63EE"
        text: "#FFFFFF"
      cards_font: Roboto
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Shanghai
      locale: en
      fallback_to_build_date: true
  - git-committers:
      repository: ai-shifu/markdown-flow
      branch: main
      enabled: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Getting Started:
    - Introduction: index.md
    - Core Concepts: getting-started/concepts.md
    - Quick Start: getting-started/quick-start.md
    - Integration: getting-started/integration.md
    - Next Steps: getting-started/next-steps.md
  - Specification:
    - Overview: specification/overview.md
    - How It Works: specification/how-it-works.md
    - Variables: specification/variables.md
    - Buttons & Input: specification/button-input.md
    - Preserved Output: specification/preserved-output.md
  - SDKs:
    - Overview: sdks/index.md
    - JavaScript:
      - markdown-flow-ui (React): sdks/javascript/markdown-flow-ui.md
      - remark-flow (React): sdks/javascript/remark-flow.md
      - markdown-it-flow (Vue/Vanilla): sdks/javascript/markdown-it-flow.md
    - Python: sdks/python.md
    - Go: sdks/go.md
  - Examples:
    - Overview: examples/index.md
    - Education: examples/education.md
    - Storytelling: examples/storytelling.md
    - Forms & Surveys: examples/forms.md
    - Documentation: examples/documentation.md
    - Consultation: examples/consultation.md
  - Ecosystem:
    - Overview: ecosystem/index.md
